import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as MailComposer from 'expo-mail-composer';
import { ExportFormat } from '../types';
import { getExportFilename } from './csvGenerator';

export type DeliveryMethod = 'email' | 'download' | 'share';

interface DeliveryResult {
  success: boolean;
  message: string;
}

/**
 * Write CSV content to a temporary file and deliver it via the chosen method.
 * Temp files are cleaned up after delivery.
 */
export async function deliverCSV(
  csvContent: string,
  format: ExportFormat,
  method: DeliveryMethod
): Promise<DeliveryResult> {
  const filename = getExportFilename(format);
  const tempFile = new File(Paths.cache, filename);

  // Validate filename to prevent path traversal
  if (/[\/\\]|\.\./.test(filename) || filename.length > 255) {
    return { success: false, message: 'Invalid export filename.' };
  }

  try {
    // Write CSV to temp file
    tempFile.write(csvContent);

    switch (method) {
      case 'email':
        return await deliverViaEmail(tempFile, filename, format);
      case 'share':
        return await deliverViaShare(tempFile);
      case 'download':
        return deliverViaDownload(tempFile, filename);
      default:
        return { success: false, message: 'Unknown delivery method.' };
    }
  } catch (error) {
    return {
      success: false,
      message: 'Failed to export CSV. Please try again.',
    };
  } finally {
    // Clean up temp file (only if it wasn't moved by download)
    if (method !== 'download') {
      try {
        if (tempFile.exists) {
          tempFile.delete();
        }
      } catch {
        // Best-effort cleanup
      }
    }
  }
}

async function deliverViaEmail(
  file: File,
  filename: string,
  format: ExportFormat
): Promise<DeliveryResult> {
  const isAvailable = await MailComposer.isAvailableAsync();
  if (!isAvailable) {
    return {
      success: false,
      message: 'Email is not available on this device. Try Share instead.',
    };
  }

  const formatLabel = {
    custom: 'Custom Excel',
    shopify: 'Shopify Import',
    ebay: 'eBay/Depop',
  }[format];

  await MailComposer.composeAsync({
    subject: `Vocis Inventory Export - ${formatLabel}`,
    body: `Attached is your inventory export in ${formatLabel} format.\n\nGenerated by Vocis.`,
    attachments: [file.uri],
  });

  return {
    success: true,
    message: 'Email compose opened with CSV attached.',
  };
}

async function deliverViaShare(file: File): Promise<DeliveryResult> {
  const isAvailable = await Sharing.isAvailableAsync();
  if (!isAvailable) {
    return {
      success: false,
      message: 'Sharing is not available on this device.',
    };
  }

  await Sharing.shareAsync(file.uri, {
    mimeType: 'text/csv',
    dialogTitle: 'Share Vocis Export',
    UTI: 'public.comma-separated-values-text',
  });

  return {
    success: true,
    message: 'CSV shared successfully.',
  };
}

function deliverViaDownload(
  tempFile: File,
  filename: string
): DeliveryResult {
  // Copy to document directory so it persists and is accessible via Files app
  const destFile = new File(Paths.document, filename);
  if (destFile.exists) {
    destFile.delete();
  }
  tempFile.copy(destFile);

  return {
    success: true,
    message: `CSV saved as "${filename}". Find it in your device files.`,
  };
}
